# Site settings
title: "BMGT_205"
email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#    Appears in your document head meta (for Google search results)
#    and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: 
#github_username:  

# Build settings
source: .
destination: _site

# collections_dir: modules

collections:
  modules:
    output: true  

# resources:
#    output: false
  starting:
   output: true

#exclude: [dir, file, ...]
#include: [".htaccess"]
markdown: kramdown

#{% assign collection = 'modules' %}
#{% for p in site.{{collection}} %}
#  <p>{{p.title}}</p>
#{% endfor %}

#{% for character in p.site.data.characters %}
#    <div class="4u">
#        <section class="box">
#            <span class="image featured"><img src="{{character.image}}" alt="" /></span>
#            <header>
#                <h3>{{character.name}}</h3>
#            </header>
#            <p>{{character.description}}</p>
#        </section>
#    </div>
# {% endfor %}