# Site settings
lsi: false
safe: true
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
#exclude: [dir, file, ...]
#include: [".htaccess"]
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

title: "Sample Course"
email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#    Appears in your document head meta (for Google search results)
#    and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
source: .
destination: _site

# collections_dir: modules
collections:
  modules:
    output: true  




